### ISSUE TITLE
Resolve Doma artifacts with Quarkus Universe BOM

### ISSUE THREAD

**Issue by ghost** [quarkiverse/quarkus-doma#224]
For most dependencies, we only need to declare `implementation(enforcedPlatform("io.quarkus:quarkus-universe-bom:X.Y.Z"))` only in `Gradle` in order to resolve all `Quarkus` dependencies released with the `Quarkus` version in question.

This doesn't work currently with `io.quarkiverse.doma:quarkus-doma`.

Would it be possible to align Doma releases in such way?

**Comment by nakamura-to** [comment]
Thanks for your feedback.

quarkus-doma has a different release cycle from Quarkus. 
Therefore, I believe it cannot be included in the Quarkus Universe BOM.
