### ISSUE TITLE
Inviting a new contributor

### ISSUE THREAD

**Issue by nakamura-to** [quarkiverse/quarkus-doma#256]
@quarkiverse/quarkiverse-owners I would like to invite a new contributor. Could you grant @orekyuu write access to this repository?

**Comment by gastaldi** [comment]
I've created https://github.com/quarkiverse/quarkiverse-devops/pull/277 for your appreciation. Note that any quarkiverse member can create PRs there

**Comment by nakamura-to** [comment]
Thank you!
